[[rules]]
id = "senha"
description = "Detecta palavras relacionadas a senha em português"
regex = "(?i)(senha)"
path = ".*"
tags = ["password"]

[[rules]]
id = "password"
description = "Detecta palavras relacionadas a senha em inglês"
regex = "(?i)(password)"
path = ".*"
tags = ["password"]

[[rules]]
id = "api_key"
description = "Detecta chaves de API genéricas"
regex = "(?i)(api|key|token)[\\s=:]+[A-Za-z0-9]{32,}"
path = ".*"
tags = ["api_key", "token"]

[[rules]]
id = "github_token"
description = "Detecta tokens de acesso pessoal do GitHub"
regex = "(?i)ghp_[A-Za-z0-9]{36}"
path = ".*"
tags = ["github_token"]

[[rules]]
id = "aws_access_key"
description = "Detecta AWS Access Key ID"
regex = "(?i)AKIA[0-9A-Z]{16}"
path = ".*"
tags = ["aws_key"]

[[rules]]
id = "aws_secret_key"
description = "Detecta AWS Secret Access Key"
regex = "(?i)(AWS_SECRET_ACCESS_KEY|aws_secret_access_key)[\\s]*=[\\s]*[A-Za-z0-9/+=]{40}"
path = ".*"
tags = ["aws_secret"]

[allowlist]
paths = []